== Job-Konfiguration

[.lead]
Konfiguration eines Batch-Jobs (Java-Config)

[source, java, indent=0]
----
include::{samples}/src/main/java/com/anderscore/goldschmiede/springbatch/samples/exec/RetryJobConfig.java[tag=config]
----

<1> `DefaultBatchConfigurer` bietet _create_-Methoden für JobRepository, JobLauncher, TransactionManager etc.

=== Komponenten zur Job-Konfiguration

[plantuml, BatchConfigurer, svg, height=760]
....
interface BatchConfigurer {
    getJobLauncher(): JobLauncher
    getJobRepository(): JobRepository
    getJobExplorer(): JobExplorer
    getTransactionManager(): PlatformTransactionManager
}
interface DataSource
interface PlatformTransactionManager
interface JobRepository
interface JobLauncher
interface JobExplorer

class DefaultBatchConfigurer {
    #createJobRepository(): JobRepository
    #createJobLauncher(): JobLauncher
    #createJobExplorer(): JobExplorer
}

BatchConfigurer <|. DefaultBatchConfigurer

DefaultBatchConfigurer o-> "1" DataSource: dataSource
DefaultBatchConfigurer o--> "1" PlatformTransactionManager: transactionManager
DefaultBatchConfigurer o--> "1" JobRepository: jobRepository
DefaultBatchConfigurer o--> "1" JobLauncher: jobLauncher
DefaultBatchConfigurer o--> "1" JobExplorer: jobExplorer

JobRepository "1" <-- StepBuilderFactory: jobRepository
PlatformTransactionManager "1" <-- StepBuilderFactory: transactionManager

JobRepository "1" <-- JobBuilderFactory: jobRepository
....

=== Konfiguration eines Steps

[source, java, indent=0]
----
include::{samples}/src/main/java/com/anderscore/goldschmiede/springbatch/samples/exec/RetryJobConfig.java[tag=step]
----

=== StepBuilder

[plantuml, StepBuilder, svg, height=760]
....
hide empty description
[*] -> StepBuilderFactory
StepBuilderFactory -> StepBuilder: get
StepBuilder -> SimpleStepBuilder: chunk
note top
    Erzeugt TaskletStep
    mit ChunkOrientedTasklet,
    und SimpleChunkProvider
    SimpleChunkProcessor
end note

SimpleStepBuilder -> FaultTolerantStepBuilder: faultTolerant
note top
    Erzeugt TaskletStep
    mit ChunkOrientedTasklet,
    und FaultTolerantChunkProvider
    FaultTolerantChunkProcessor
end note


StepBuilder --> TaskletStepBuilder: tasklet
note bottom: Erzeugt TaskletStep

StepBuilder --> JobStepBuilder: job
note bottom: Erzeugt JobStep

StepBuilder --> PartitionStepBuilder: partitioner
note bottom: Erzeugt PartitionStep

StepBuilder --> FlowStepBuilder: flow
note bottom
    Erzeugt FlowStep mit Flow, der selbst
    wiederum beliebige Steps (z. B. TaskletStep,
    DecisionStep, FlowStep, ...) enthalten kann
end note
....

=== Konfiguration eines Jobs

[source, java, indent=0]
----
include::{samples}/src/main/java/com/anderscore/goldschmiede/springbatch/samples/exec/RetryJobConfig.java[tag=job]
----

=== JobBuilder

[plantuml, JobBuilder, svg, width=1600]
....
hide empty description
[*] -> JobBuilderFactory
JobBuilderFactory -> JobBuilder: get
JobBuilder -> SimpleJobBuilder: start(Step)
JobBuilder --> JobFlowBuilder: start(Flow)
note left
Erweitert FlowBuilder
end note
JobBuilder --> JobFlowBuilder: flow(Step)
SimpleJobBuilder -> SimpleJobBuilder: start(Step)
SimpleJobBuilder -> SimpleJobBuilder: next(Step)
SimpleJobBuilder --> JobFlowBuilder: start(Flow)
SimpleJobBuilder -> Job: build
JobFlowBuilder --> JobFlowBuilder: start
JobFlowBuilder --> JobFlowBuilder: next
JobFlowBuilder --> FlowJobBuilder: end
FlowJobBuilder -> Job: build
Job -> [*]
....

[.columns]
== Flows 

--
[.lead]
Job mit Flow

[source, java, indent=0]
----
include::{samples}/src/main/java/com/anderscore/goldschmiede/springbatch/samples/exec/FlowJobConfig.java[tag=flow]
----
--

--
[plantuml, FlowBuilder, svg, height=800]
....
start
:step 1;
fork
    :step 2a 1;
    :step 2a 2;
fork again
    :step 2b;
end fork
:step 3;
if (failed?) then (yes)
  :step 3x;
endif
:step 4;
stop
....
--

== Transaktionen und Wiederanlauf

[.lead]
Konfiguration des Transaktions- und Wiederanlaufverhaltens

[plantuml, TxConfig, svg, width=100%]
....
class StepBuilderHelper {
    allowStartIfComplete(allowStartIfComplete: boolean)
    startLimit(startLimit: int)
    transactionManager(transactionManager: PlatformTransactionManager)
}

class AbstractTaskletStepBuilder {
    transactionAttribute(transactionAttribute: TransactionAttribute)
    exceptionHandler(exceptionHandler: ExceptionHandler)
}

StepBuilderHelper <|- AbstractTaskletStepBuilder

class SimpleStepBuilder {
    readerIsTransactionalQueue()
}

AbstractTaskletStepBuilder <|-- SimpleStepBuilder

class FaultTolerantStepBuilder {
    processorNonTransactional()
    skip(type: Class<? extends Throwable>)
    noSkip(type: Class<? extends Throwable>)
    skipLimit(skipLimit: int)
    skipPolicy(skipPolicy: SkipPolicy)
    retry(type: Class<? extends Throwable>)
    noRetry(type: Class<? extends Throwable>)
    noRollback(type: Class<? extends Throwable>)
    retryLimit(retryLimit: int)
    retryPolicy(retryPolicy: RetryPolicy)
    backOffPolicy(backOffPolicy: BackOffPolicy)
    keyGenerator(keyGenerator: KeyGenerator)
}

FaultTolerantStepBuilder -|> SimpleStepBuilder

class JobBuilderHelper {
    preventRestart()
}

JobBuilderHelper <|-- JobBuilder 
JobBuilderHelper <|-- SimpleJobBuilder
....

== Listener

[.lead]
Listener Interfaces und deren Registrierung

[plantuml, Listener, svg, width=100%]
....
class StepBuilderHelper {
    listener(listener: StepExecutionListener): StepBuilderHelper
    listener(listener: Object): StepBuilderHelper
}
note left
Es können beliebige Objekte
mit entsprechenden Listener
Annotationen registriert werden.
end note

class AbstractTaskletStepBuilder {
    stream(stream: ItemStream): AbstractTaskletStepBuilder
    listener(listener: ChunkListener): AbstractTaskletStepBuilder
}

StepBuilderHelper <|-- AbstractTaskletStepBuilder

class SimpleStepBuilder {
    listener(listener: ItemProcessListener): SimpleStepBuilder
    listener(listener: ItemReadListener): SimpleStepBuilder
    listener(listener: ItemWriteListener): SimpleStepBuilder
}

AbstractTaskletStepBuilder <|-- SimpleStepBuilder
note left
Reader, Writer und Processer werden
immer als Listener registriert, sofern
sie ein Listener-Interface implementieren
oder entsprechend Annotierte Methoden haben.
end note

class FaultTolerantStepBuilder {
    listener(listener: RetryListener)
    listener(listener: SkipListener)
}

SimpleStepBuilder <|-- FaultTolerantStepBuilder

interface JobListener {
    beforeJob()
    afterJob()
}

interface ItemStream {
    update(arg0: ExecutionContext)
    close()
    open(arg0: ExecutionContext)
}

ItemStream <. AbstractTaskletStepBuilder

interface StepListener {
}

interface StepExecutionListener {
    beforeStep(arg0: StepExecution)
    afterStep(arg0: StepExecution): ExitStatus
}

StepExecutionListener -|> StepListener

interface ChunkListener {
    beforeChunk(arg0: ChunkContext)
    afterChunk(arg0: ChunkContext)
    afterChunkError(arg0: ChunkContext)
}

StepListener <|-- ChunkListener

interface StepListener {
}

interface ItemReadListener {
    beforeRead()
    afterRead(arg0: Object)
    onReadError(arg0: Exception)
}

StepListener <|--- ItemReadListener

interface ItemProcessListener {
    beforeProcess(arg0: Object)
    onProcessError(arg0: Object, arg1: Exception)
    afterProcess(arg0: Object, arg1: Object)
}

StepListener <|--- ItemProcessListener

interface ItemWriteListener {
    afterWrite(arg0: List)
    beforeWrite(arg0: List)
    onWriteError(arg0: Exception, arg1: List)
}

StepListener <|--- ItemWriteListener

interface SkipListener {
    onSkipInProcess(arg0: Object, arg1: Throwable)
    onSkipInRead(arg0: Throwable)
    onSkipInWrite(arg0: Object, arg1: Throwable)
}

StepListener <|-- SkipListener

class StepListenerSupport {
}

StepExecutionListener <|.. StepListenerSupport

ChunkListener <|.. StepListenerSupport

ItemReadListener <|.. StepListenerSupport

ItemProcessListener <|.. StepListenerSupport

ItemWriteListener <|.. StepListenerSupport

SkipListener <|.. StepListenerSupport

interface RetryListener {
    close(arg0: RetryContext, arg1: RetryCallback, arg2: Throwable)
    open(arg0: RetryContext, arg1: RetryCallback): boolean
    onError(arg0: RetryContext, arg1: RetryCallback, arg2: Throwable)
}

RetryListener <. FaultTolerantStepBuilder
....

== Scope

[.lead]
@StepScope und @JobScope

* Erzeugt Bean für Lebenszyklus eines Steps bzw. eines Jobs
* Ermöglicht _late binding_ über `@Value("++#++{jobParameters[input.file.name]}")`, +
  `@Value("++#++{jobExecutionContext[key]}")` oder +
  `@Value("++#++{stepExecutionContext[minValue]}")`
* `@StepScope` bei Reader, Processor oder Writer in Kombination mit Partitionierung sinnvoll

include::index.adoc[]