== Job-Konfiguration

[.lead]
Konfiguration eines Batch-Jobs (Java-Config)

[source, java, indent=0]
----
include::{samples}/src/main/java/com/anderscore/goldschmiede/springbatch/samples/exec/RetryJobConfig.java[tag=config]
----

=== Komponenten zur Job-Konfiguration

[plantuml, BatchConfigurer, svg, height=760]
....
interface BatchConfigurer {
    getJobLauncher(): JobLauncher
    getJobRepository(): JobRepository
    getJobExplorer(): JobExplorer
    getTransactionManager(): PlatformTransactionManager
}
interface DataSource
interface PlatformTransactionManager
interface JobRepository
interface JobLauncher
interface JobExplorer

BatchConfigurer <|. DefaultBatchConfigurer

DefaultBatchConfigurer o-> "1" DataSource: dataSource
DefaultBatchConfigurer o--> "1" PlatformTransactionManager: transactionManager
DefaultBatchConfigurer o--> "1" JobRepository: jobRepository
DefaultBatchConfigurer o--> "1" JobLauncher: jobLauncher
DefaultBatchConfigurer o--> "1" JobExplorer: jobExplorer

JobRepository "1" <-- StepBuilderFactory: jobRepository
PlatformTransactionManager "1" <-- StepBuilderFactory: transactionManager

JobRepository "1" <-- JobBuilderFactory: jobRepository
....

=== Konfiguration eines Steps

[source, java, indent=0]
----
include::{samples}/src/main/java/com/anderscore/goldschmiede/springbatch/samples/exec/RetryJobConfig.java[tag=step]
----

=== StepBuilder

[plantuml, StepBuilder, svg, height=760]
....
hide empty description
[*] -> StepBuilderFactory
StepBuilderFactory -> StepBuilder: get
StepBuilder -> SimpleStepBuilder: chunk
note top
    Erzeugt TaskletStep
    mit ChunkOrientedTasklet,
    und SimpleChunkProvider
    SimpleChunkProcessor
end note

SimpleStepBuilder -> FaultTolerantStepBuilder: faultTolerant
note top
    Erzeugt TaskletStep
    mit ChunkOrientedTasklet,
    und FaultTolerantChunkProvider
    FaultTolerantChunkProcessor
end note


StepBuilder --> TaskletStepBuilder: tasklet
note bottom: Erzeugt TaskletStep

StepBuilder --> JobStepBuilder: job
note bottom: Erzeugt JobStep

StepBuilder --> PartitionStepBuilder: partitioner
note bottom: Erzeugt PartitionStep

StepBuilder --> FlowStepBuilder: flow
note bottom
    Erzeugt FlowStep mit Flow, der selbst
    wiederum beliebige Steps (z. B. TaskletStep,
    DecisionStep, FlowStep, ...) enthalten kann
end note
....

=== JobBuilder

[plantuml, JobBuilder, svg, width=1600]
....
hide empty description
[*] -> JobBuilderFactory
JobBuilderFactory -> JobBuilder: get
JobBuilder -> SimpleJobBuilder: start(Step)
JobBuilder --> JobFlowBuilder: start(Flow)
note left
Erweitert FlowBuilder
end note
JobBuilder --> JobFlowBuilder: flow(Step)
SimpleJobBuilder -> SimpleJobBuilder: start(Step)
SimpleJobBuilder -> SimpleJobBuilder: next(Step)
SimpleJobBuilder --> JobFlowBuilder: start(Flow)
SimpleJobBuilder -> Job: build
JobFlowBuilder --> JobFlowBuilder: start
JobFlowBuilder --> JobFlowBuilder: next
JobFlowBuilder --> FlowJobBuilder: end
FlowJobBuilder -> Job: build
Job -> [*]
....

[.columns]
== Flows 

--
[.lead]
Job mit Flow

[source, java, indent=0]
----
include::{samples}/src/main/java/com/anderscore/goldschmiede/springbatch/samples/exec/FlowJobConfig.java[tag=flow]
----
--

--
[plantuml, FlowBuilder, svg, height=800]
....
start
:step 1;
fork
    :step 2a 1;
    :step 2a 2;
fork again
    :step 2b;
end fork
:step 3;
if (failed?) then (yes)
  :step 3x;
endif
:step 4;
stop
....
--

include::index.adoc[]