== Chunkverarbeitung und Fehlerbehandlung

[.lead]
Wozu Chunkverarbeitung?

[%step]
- Transaktion zu groß (wenn der ganze Job in einer Transaktion läuft)
** Rollback Segment läuft über
** Bei Fehler wird alles zurückgerollt
- Transaktionen zu klein (wenn jeder Datensatz in einer Transaktion verarbeitet wird)
** Performance
** Spring-Batch aktualisiert Status mit jeder Transaktion
- => Lösung: Daten in Chunks verarbeiten

=== ChunkOrientedTasklet

[plantuml, ChunkOrientedTasklet, svg, width=1800]
....
interface Tasklet
interface RepeatOperations
note bottom: Repeat\nTemplate
interface ChunkProvider<I>
interface ChunkProcessor<I>

class ChunkOrientedTasklet<I>
class SimpleChunkProvider<I>
class FaultTolerantChunkProvider<I>
class SimpleChunkProcessor<I, O>
class FaultTolerantChunkProcessor<I, O>

interface ItemReader<I>
interface ItemProcessor<I, O>
interface ItemWriter<O>
interface SkipPolicy

ChunkProvider "1" <--o ChunkOrientedTasklet
Tasklet <|.. ChunkOrientedTasklet
ChunkProcessor "1" <--o ChunkOrientedTasklet

ChunkProvider <|.. SimpleChunkProvider
SimpleChunkProvider <|-- FaultTolerantChunkProvider
ChunkProcessor <|.. SimpleChunkProcessor
SimpleChunkProcessor <|-- FaultTolerantChunkProcessor

FaultTolerantChunkProvider o-> "1" SkipPolicy
SkipPolicy "2" <-o FaultTolerantChunkProcessor

ItemReader "1" <--o SimpleChunkProvider
RepeatOperations "1" <-o SimpleChunkProvider
SimpleChunkProcessor o-> "1" ItemProcessor
SimpleChunkProcessor o--> "1" ItemWriter

SimpleChunkProvider -[hidden]> ChunkOrientedTasklet
ChunkOrientedTasklet -[hidden]> SimpleChunkProcessor
ItemProcessor -[hidden]- ItemWriter
....

=== Chunkverarbeitung

[plantuml, ChunkExec, svg, width=1800]
....
loop until FINISHED (RepeatTemplate)
    TaskletStep -> TransactionTemplate: execute
    activate TransactionTemplate
    
    TransactionTemplate -> ChunkOrientedTasklet: execute

    activate ChunkOrientedTasklet
    ChunkOrientedTasklet -> SimpleChunkProvider: provide
    
    loop chunk-size times (RepeatTemplate)
        SimpleChunkProvider -> ItemReader: read
    end

    ChunkOrientedTasklet -> SimpleChunkProcessor: process
    activate SimpleChunkProcessor
    
    loop for each item
        SimpleChunkProcessor -> ItemProcessor: process
    end
   
    SimpleChunkProcessor -> ItemWriter: write 
    deactivate SimpleChunkProcessor
    
    deactivate ChunkOrientedTasklet
    
    deactivate TransactionTemplate
end
....

=== Reader/Processor/Writer

* Reader: Rückgabewert `null` signalisiert Ende
* Processor: Rückgabewert `null` überspringt Datensatz (Filter)
* Verhalten von Spring-Batch im Ausnahmefall wird über Exceptions gesteuert

=== Welche Fehler gibt es?

Und wie soll damit umgegangen werden?

=== Fehler und wünschenswertes Fehlerverhalten

|===
|Datensatz überpringen|Erneut versuchen|Job abbrechen

|Programmierfehler|Verbindungsunterbrechung|Systemausfall
|Ungültiges Zeichen in Datensatz|Neustart eines Servers|Fehlende Berechtigung
|Datei defekt|Datensatz gesperrt
|Nicht berücksichtigte Exception|
|===

=== Überspringen von Datensätzen

Demo...

=== RetryTemplate -- Noch ein Framework für eine Schleife...

[plantuml, RetryTemplate, svg, width=1700]
....
interface RetryOperations {
    execute(retryCallback: RetryCallback<T, E>): T
    execute(retryCallback: RetryCallback<T, E>, retryState: RetryState): T
    execute(retryCallback: RetryCallback<T, E>, recoveryCallback: RecoveryCallback<T>): T
    execute(retryCallback: RetryCallback<T, E>, recoveryCallback: RecoveryCallback<T>, retryState: RetryState): T
}

interface BackOffPolicy
interface RetryPolicy
interface RetryListener
interface RetryContextCache

interface RetryCallback<T, E> {
    doWithRetry(context: RetryContext): T
}

interface RetryContext
interface AttributeAccessor
interface RetryState
class DefaultRetryState {
    key: Object
}
note right: Enthält Item-Key

interface RecoveryCallback<T> {
    recover(context: RetryContext): T
}

RetryOperations <|.. RetryTemplate 
RetryPolicy "1" <-* RetryTemplate
RetryTemplate *--> "1" BackOffPolicy 
RetryTemplate *--> "0..n" RetryListener
RetryTemplate *-> "1" RetryContextCache

RetryPolicy <|.. SimpleRetryPolicy
RetryPolicy <|.. TimeoutRetryPolicy

BackOffPolicy <|.. NoBackOffPolicy
BackOffPolicy <|.. FixedBackOffPolicy
BackOffPolicy <|.. UniformRandomBackOffPolicy
BackOffPolicy <|.. ExponentialBackOffPolicy

RetryCallback ..> RetryContext 
RecoveryCallback ..> RetryContext 
AttributeAccessor <|- RetryContext
RetryContext --> RetryContext: parent

RetryContext -- RetryState
RetryState <.. DefaultRetryState

note as N
ContextCache speichert RetryContext
mit RetryState (Item) als Key 
end note

RetryContextCache .. N
RetryContext .. N
N . RetryState
....

=== Chunkverarbeitung mit Retry

[plantuml, ChunkExecWithRetry, svg, width=1800]
....
loop until FINISHED (RepeatTemplate)
    TaskletStep -> TransactionTemplate: execute
    activate TransactionTemplate
    
    TransactionTemplate -> ChunkOrientedTasklet: execute

    activate ChunkOrientedTasklet
    ChunkOrientedTasklet -> SimpleChunkProvider: provide
    
    loop chunk-size times (RepeatTemplate)
        SimpleChunkProvider -> ItemReader: read
    end

    ChunkOrientedTasklet -> SimpleChunkProcessor: process
    activate SimpleChunkProcessor
    
    loop for each item
        loop RetryTemplate
            SimpleChunkProcessor -> ItemProcessor: process
        end
        note right: with\nretry
    end
   
    loop RetryTemplate
        SimpleChunkProcessor -> ItemWriter: write
    end 
    note right: with\nretry
    
    deactivate SimpleChunkProcessor
    
    deactivate ChunkOrientedTasklet
    
    deactivate TransactionTemplate
end
....

include::index.adoc[]