== Operations

[.lead]
Operations Aufgaben

[%step]
* Job Starten
* Prüfen, ob Job erfolgreich ausgeführt wurde
* Fehlerursache nachsehen
* Statistik erstellen
* Job anhalten bzw. forsetzen
* Job abbrechen
* Wiederanlauf versuchen

=== Operations Interfaces

[plantuml, Operations, svg, height=760]
....
interface JobLauncher {
    run(job: Job, jobParameters: JobParameters): JobExecution
}

JobLauncher <|.. SimpleJobLauncher
note bottom
Kann Job synchron oder asynchron ausführen,
je nachdem welcher TaskExecutor gesetzt ist 
end note

interface JobExplorer {
    getJobNames(): List<String>
    getJobInstances(jobName: String, start: int, count: int): List<JobInstance>
    findJobInstancesByJobName(jobName: String, start: int, count: int): List<JobInstance>
    getJobInstanceCount(jobName: String): int
    getJobInstance(instanceId: Long): JobInstance
    getJobExecutions(jobInstance: JobInstance): List<JobExecution>
    getJobExecution(executionId: Long): JobExecution
    findRunningJobExecutions(jobName: String): Set<JobExecution>
    getStepExecution(executionId: Long, stepExecutionId: Long): StepExecution
}

JobExplorer <|.. SimpleJobExplorer

JobLauncher <-- CommandLineJobRunner
JobExplorer <-- CommandLineJobRunner
....

=== Eindeutigen _run.id_ Parameter konfigurieren

[source, java, indent=0]
.LauncherConfig.java
----
include::{samples}/src/main/java/com/anderscore/goldschmiede/springbatch/samples/op/LauncherConfig.java[tag=incrementer]
----

=== Mit eindeutiger _run.id_ starten

[source, java, indent=0]
.LauncherConfig.java
----
include::{samples}/src/test/java/com/anderscore/goldschmiede/springbatch/samples/op/LauncherTest.java[tag=launch]
----

=== JobOperator

[plantuml, JobOperator, svg, height=760]
....
interface JobLauncher
interface JobExplorer
interface JobRegistry
interface JobRepository

interface JobOperator {
    start(jobName: String, parameters: String): Long
    restart(executionId: long): Long
    startNextInstance(jobName: String): Long
    stop(executionId: long): boolean
    abandon(executionId: long): JobExecution
    getJobNames(): Set<String>
    getParameters(executionId: long): String
    getJobInstances(jobName: String, start: int, count: int): List<Long>
    getExecutions(instanceId: long): List<Long>
    getRunningExecutions(jobName: String): Set<Long>
    getSummary(executionId: long): String
    getStepExecutionSummaries(executionId: long): Map<Long, String>
}

JobOperator <|.. SimpleJobOperator

SimpleJobOperator --> JobLauncher
SimpleJobOperator --> JobExplorer
SimpleJobOperator --> JobRegistry
SimpleJobOperator --> JobRepository
....

=== JobOperator konfigurieren

[source, java, indent=0]
.OperatorConfig.java
----
include::{samples}/src/main/java/com/anderscore/goldschmiede/springbatch/samples/op/OperatorConfig.java[tag=operator]
----

=== JobOperator verwenden

[source, java, indent=0]
.OperatorConfig.java
----
include::{samples}/src/test/java/com/anderscore/goldschmiede/springbatch/samples/op/OperatorTest.java[tag=operator]
----

include::index.adoc[]